# Generated by Django 4.2.7 on 2023-11-05 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_title', models.CharField(max_length=100)),
                ('entry_subject', models.CharField(max_length=100)),
                ('entry', models.CharField(max_length=2000)),
            ],
        ),
    ]
